language: bash
services: docker

env:
  - VERSION=5.6 IMAGES="php fpm apache-php"
  - VERSION=7.0 IMAGES="php fpm apache-php"
  - VERSION=7.1 IMAGES="php fpm apache-php"
  - VERSION=7.2 IMAGES="php fpm"
  - VERSION=8 IMAGES="node"
  - VERSION=10 IMAGES="node"

script:
  - ./.ci/build_images.sh
  - ./.ci/run_tests.sh
